services:
  db:
    image: mysql
    restart: always
    ports:
      - '3304:3306'
    environment:
      MYSQL_DATABASE: mascotas
      MYSQL_ROOT_PASSWORD: mascotas
    volumes:
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql